version: 2
updates:
  # Enable version updates for API
  - package-ecosystem: uv
    # Look for `pyproject.toml` and `uv.lock` file in the `root` directory
    directory: /
    schedule:
      interval: daily

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: /
    schedule:
      interval: weekly
