[project]
name = "dbt-fusion-package-tools"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gitpython>=3.1.45",
    "mashumaro>=3.17",
    "pyyaml>=6.0.2",
    "dbt-protos>=1.0.410",
]

dynamic = ["version"]

[project.scripts]
dbt-fusion-package-tools = "dbt_fusion_package_tools:main"
dbt-fusion-package-schema-compat = "dbt_fusion_package_tools.check_parse_conformance:main"

[tool.uv]
package = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "scm"
version_format = "pdm_build:format_version"

[project.optional-dependencies]
docs = [
    "pydocstyle>=6.3.0",
]
